import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
result = np.dot(arr1,arr2)
print("Resultant array after matrix multiplication:")
print(result)
print("SUM",np.sum(result))
print("MEAN",np.mean(result))
print("STANDARD DEVIATION",np.std(result))
print("VARIANCE",np.var(result))
print("MINIMUM VALUE",np.min(result))
print("MAXIMUM VALUE",np.max(result))
print("ARGMAX",np.argmax(result))
print("ARGMIN",np.argmin(result))
print("TRANSPOSE",np.transpose(result))
print("INVERSE",np.linalg.inv(result))
print("DETERMINANT",np.linalg.det(result))
print("MULTIPLE",np.multiply(arr1,arr2))
print("ADD",np.add(arr1,arr2))
print("SUBTRACT",np.subtract(arr1,arr2))
print("DIVIDE",np.divide(arr1,arr2))
print("SQRT",np.sqrt(arr1))
print("POWER",np.power(arr1,2))
print("LOG",np.log(arr1))
print("EXP",np.exp(arr1))
print("ROUND",np.round(arr1))
print("UNIQUE",np.unique(arr1))
print("SORTED",np.sort(arr1))
print("join Array",np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))
print("shape",np.reshape(arr1,(1,9))) 
print("copy",np.copy(arr1))
print("np.where(arr1>5)",np.where(arr1>5))
print("nonzero",np.nonzero(arr1))
print("save",np.save('array.npy',arr1))
print("load",np.load('array.npy'))
print("savetxt",np.savetxt('array.txt',arr1))
print("loadtxt",np.loadtxt('array.txt'))
print("random.rand",np.random.rand(3,3))
print("random.randint",np.random.randint(1,10,(3,3)))
print("linspace",np.linspace(0,1,5))
print("arange",np.arange(0,10,2))
print("meshgrid",np.meshgrid(np.array([1,2,3]),np.array([4,5,6])))
print("diag",np.diag(arr1))
print("trace",np.trace(arr1))
print("cumsum",np.cumsum(arr1))
print("cumprod",np.cumprod(arr1))
print("clip",np.clip(arr1,3,7))
print("histogram",np.histogram(arr1,bins=3))
print("np.corrcoef(arr1.flatten(),arr2.flatten())",np.corrcoef(arr1.flatten(),arr2.flatten()))
print("convolve",np.convolve(arr1.flatten(),arr2.flatten(),'full'))
print("gradient",np.gradient(arr1))
print("hstack",np.hstack((arr1,arr2)))
print("vstack",np.vstack((arr1,arr2)))
print("dstack",np.dstack((arr1,arr2)))
print("np.split(arr1,3)",np.split(arr1,3))
print("np.array_equal(arr1,arr2)",np.array_equal(arr1,arr2))
print("np.shares_memory(arr1,arr2)",np.shares_memory(arr1,arr2))
print("np.may_share_memory(arr1,arr2)",np.may_share_memory(arr1,arr2))
print("fromfunction",np.fromfunction(lambda i,j:i+j,(3,3)))
print("fromiter",np.fromiter(range(9),dtype=int).reshape((3,3)))
print("ndenumerate",np.ndenumerate(arr1))
print("np.ndindex(arr1.shape)",np.ndindex(arr1.shape))
print("np.broadcast(arr1,arr2)",np.broadcast(arr1,arr2))
print("np.errstate(divide='ignore'))"),np.errstate(divide='ignore')
# print(np.set_printoptions(precision=2))
# print(np.get_printoptions())
# print(np.info(np.array))
# print(np.show_config())
# print(np.__version__)
# print(np.__path__)
# print(np.__file__)
# print(np.__name__)
# print(np.__doc__)
# print(np.__all__)
# print(np.__builtins__)
# print(np.__cached__)
# print(np.__loader__)
# print(np.__package__)
# # print(np.__spec__)
# # print(np.__array_ufunc__)
# # print(np.__array_function__)
# # print(np.__array_finalize__)
# # print(np.__array_wrap__)
# # print(np.__array_prepare__)
# # print(np.__array_reshape__)
# # print(np.__array_struct__)
# # print(np.__array_module__)
# # print(np.__array_namespace__)
# # print(np.__array_implementation__)
# # print(np.__array_function_dispatch__)
# # print(np.__array_ufunc_dispatch__)
# # print(np.__array_function_from_dispatcher__)
# # print(np.__array_ufunc_from_dispatcher__)
# # print(np.__array_function_signature__)
# # print(np.__array_ufunc_signature__)
# # print(np.__array_function_doc__)
# # print(np.__array_ufunc_doc__)
# # print(np.__array_function_examples__)
# # print(np.__array_ufunc_examples__)
# # print(np.__array_function_notes__)
# # print(np.__array_ufunc_notes__)
